### ISSUE TITLE
Profile templates

### ISSUE THREAD

**Issue by Svadkos** [igo95862/bubblejail#1]
It would be nice if there was a way to create profile templates. Then it would be possible to build sandbox profile for an executable using a template. For example: `bubblejail create --template=games ~/path/to/game/exec`

**Comment by igo95862** [comment]
I posted a new version today.

It will read the profiles from `~/.config/bubblejail/profiles/`. Profiles in there will have a priority over the ones in `/usr`.

You will need to git pull the new version of PKGBUILD since build system has changed. There are as well some [breaking changes](https://github.com/igo95862/bubblejail/blob/master/docs/breaking_changes.md) as well as new GUI to configure or create instances.
