### ISSUE TITLE
Changed install location with 0.9.0

### ISSUE THREAD

**Issue by rusty-snake** [igo95862/bubblejail#110]
### Output of `bubblejail --version`

0.9.0

### Your distro name and version

Fedora 40

### Description

I'm not sure if this is a intentional change, just wanted to let you know.
I did not used the `allow-site-packages-dir` feature. However, with 0.9.0 the install location of bubblejail has changed from `/usr/lib64` ("`libdir`" as used by Fedora) to `/usr/lib` (hardcoded `lib`?). I can catch up downstream, `/usr/lib` is maybe the correcter path anyway, have to check that (lib = architecture independent i.e. python, lib64 = architecture dependent i.e. python with C dependency). Just wanted to let you know I case of a unintentional change.

**Comment by igo95862** [comment]
Hello @rusty-snake 

This is probably because in the new default options are hard coding the `lib/` prefix.

https://github.com/igo95862/bubblejail/blob/fc5dd5a2e8ef962b2b6da75beeb2b364926fc831/meson.build#L7-L8

The issue this is one of few ways to install the python packages outside the default site packages. See https://github.com/mesonbuild/meson/discussions/13132

> have to check that (lib = architecture independent i.e. python, lib64 = architecture dependent i.e. python with C dependency).

python-lxns is architecture dependent if you are using it as a subproject. I included it in the source archive to make it easier to package bubblejail.

**Comment by rusty-snake** [comment]
Is it possible to somehow/somewhere change them to `get_option('libdir') / 'bubblejail/python-packages'`? Or should I just patch/override them with values from rpmbuild-macros?

---

OT: https://github.com/igo95862/bubblejail/blob/fc5dd5a2e8ef962b2b6da75beeb2b364926fc831/tools/run_test_bubblejail.py#L24

**Comment by igo95862** [comment]
`project()` has to the first function call. Trying to call anything before or inside will raise an error.

One other solution is to not have the default options at all and make PKGBUILD pass the version independent location. Or meson will add option to use different directory than site packages. However, they don't really see this as useful.

 > OT: 

This is from earlier experiments with manipulating install dir. Thank you for bring this up. I will fix it in the future.

**Comment by rusty-snake** [comment]
https://github.com/rusty-snake/fedora-extras/commit/d94d1a68ab1af0b852e0d7d024beb26374263e0c

Seems to work, thanks.
