### ISSUE TITLE
Error locating X11 socket file

### ISSUE THREAD

**Issue by gxtu** [igo95862/bubblejail#54]
### Output of `bubblejail --version`

0.7.0

### Your distro name and version

Arch Linux

### Description

When launching a bubblejail instance with the X11 service, I'm getting the following error:

```
bwrap: Can't find source path /tmp/.X11-unix/X0.0: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 32, in <module>
    bubblejail_main()
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 366, in bubblejail_main
    func(**args_dict)
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 113, in run_bjail
    async_run(
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_instance.py", line 328, in async_run_init
    raise BubblewrapRunError((
bubblejail.exceptions.BubblewrapRunError: Bubblewrap failed. Try running bubblejail in terminal to see the exact error.
```

It seems like Bubblejail can't find the X11 socket. It's looking for `/tmp/.X11-unix/X0.0`, because my `DISPLAY` environment variable contains `:0.0` (I assume this is because I have multiple monitors connected). The actual socket file is still located at `/tmp/.X11-unix/X0` though.

I was able to fix this by modifying the corresponding code in `services.py` to only parse out the display number:
```
display_env = environ['DISPLAY']
display_host, display_nums = display_env.split(':')
display_num, screen_num = display_nums.split('.')
yield Bind(f"/tmp/.X11-unix/X{display_num}")
```

**Comment by igo95862** [comment]
Hello @gxtu 

Current code does indeed only handle single X11 screen. Thank you for pointing this out.

I found the documentation of `DISPLAY` environmental variable documentation:

https://man.archlinux.org/man/X.7#DISPLAY_NAMES

**Comment by igo95862** [comment]
Should be fixed in 150c1e8204a000183fba4ee62378680e5caadfba. @gxtu can you give it a test?

I found something strange. If you set `DISPLAY` to `unix/localhost:0.0` and not bind socket inside sandbox the windowing system will still work if network service is enabled even though `tcp/` protocol would not work.

**Comment by rusty-snake** [comment]
@igo95862 abstract unix domain socket.

Short, a Unix socket can be bound to a path in the filesystem or a path that starts with a null byte. This is a Linux specific feature where the socket lives in an abstract socket filesystem (can be inspected with ss or netstat). This filesystem is isolated by unsharing the network namespace.

It is a common way to escape a sandbox with   shared network namespace because you can often find X11 or D-Bus sockets there.

**Comment by igo95862** [comment]
TIL.

```
$ lsof -U | grep @
... @/tmp/.X11-unix/X0 type=STREAM (LISTEN)
```

> That's why people want to see slirp4netns/pasta/passt support in flatpak/bubblewrap/bubblejail/...

bubblejail has support for slirp4netns since version 0.7.0
