### ISSUE TITLE
[Req] Add catchall option to add arbitrary bwrap flags

### ISSUE THREAD

**Issue by xiota** [igo95862/bubblejail#85]
### Description

GUI could consist of a single text entry box (like a text editor) or a list of text entry boxes (similar to home share and root share) that allows arbitrary `bwrap` options to be entered.  This would allow `bwrap` features to be used that are not yet directly supported.

**Comment by igo95862** [comment]
I have an idea of adding a `debug` service that could be used to manually add arguments. (like `--debug-bwrap-args`)

**Comment by igo95862** [comment]
A `debug` service was added in f935480e47c938b99fc6ea3783972d65e19db51e

**Comment by xiota** [comment]
Note for future visitors:  To use, add the following to `services.toml`:
```
[debug]
raw_bwrap_args = [
    "--setenv",
    "X",
    "Y",
]
raw_dbus_session_args = []
raw_dbus_system_args = []
```
Each argument has to be a separate item in the list.  The following will not work:
```
[debug]
raw_bwrap_args = [
    "--setenv X Y",
]
raw_dbus_session_args = []
raw_dbus_system_args = []
```

**Comment by igo95862** [comment]
By the way you can do

```
raw_bwrap_args = [
    "--setenv", "X", "Y",
]
```

But as soon as you edit settings with GUI it will revert back to one item per line. The issue is that `tomli-w` does not preserve style. Maybe I should add support for `tomlkit` which can preserve style and comments. Image that a new created instance will have contain all the available options in the comments like for example `/etc/ssh/sshd_config` does.

**Comment by rusty-snake** [comment]
Nested array would be an second way.

```toml
raw_bwrap_args = [
    ["--setenv", "X", "Y"],
]
```

**Comment by igo95862** [comment]
```
raw_bwrap_args = [
    "--setenv", "X", "Y",
]
```

It is not a nested array. There is no second set of square brackets in my post.
